### ISSUE TITLE
full restore fails

### ISSUE THREAD

**Issue by totti4ever** [mbentley/docker-timemachine#101]
**Describe the bug**
I'm on a MacBook Pro 13", late 2013 and have to restore after the update to Big Sur lead to the black screen after sleep 🙄

Since a week I have tried every possible way I can think of to restore:
Right direct, full from scratch, after a clean install, using the migration assistant after an installation with a temporary news user... No way

I've seen many different error messages on the screen, but apple-like, non of them helpful!

No I thought of checking the server's log and I hope, you can see something in it!

**To Reproduce**
Restore from apple-R startup menu and then when it's supposed to be more or less done, it says some error occurred...

**Expected behavior**

**How you're launching your container**
```
version: "3.7"

services:

  timemachine:
    container_name: timemachine
    image: mbentley/timemachine:smb
    restart: unless-stopped
    networks:
      timemachine:
        ipv4_address: '192.168.xxx.yyy'
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    ports:
     - "137:137/udp"
     - "138:138/udp"
     - "139:139"
    environment:
      - CUSTOM_SMB_CONF=false
      - CUSTOM_USER=false
      - LOG_LEVEL=info
      - EXTERNAL_CONF=
      - HIDE_SHARES=no
      - MIMIC_MODEL=TimeCapsule8,119
      - TM_USERNAME=samba_m
      - TM_GROUPNAME=samba_m
      - TM_UID=1003 # samba_m
      - TM_GID=1007 # samba_m
      - PASSWORD=zzz
      - SET_PERMISSIONS=true
      - SHARE_NAME=TimeMachine
      - SMB_PORT=445
      - VOLUME_SIZE_LIMIT=350G
      - WORKGROUP=WORKGROUP


    volumes:
     - /datapool1/backup/backup_mac:/opt/samba_m
     - ./data/timemachine-var-lib-samba:/var/lib/samba
     - ./data/timemachine-var-cache-samba:/var/cache/samba
     - ./data/timemachine-run-samba:/run/samba


networks:
  timemachine:
    external: true

```

**Container Logs**
![Screenshot_20211010-213802~(1)](https://user-images.githubusercontent.com/49901208/136712210-7239e8a1-c87f-4222-84bb-1a9fd39e9699.jpg)

**Additional context**
