### ISSUE TITLE
Can't connect to shared drive when not using host networking mode

### ISSUE THREAD

**Issue by shred86** [mbentley/docker-timemachine#110]
**Describe the bug**
Edit: Actually seeing this issue with the host networking option enabled as well...

When attempting to use this without the `--net=host` option and just forwarding all the ports specified in the [read me,](https://github.com/mbentley/docker-timemachine), I'm unable to connect to the samba drive. Using Mac OS finder Go > Connect to server, I type in the address of my server running this container `smb://172.16.16.1` and after clicking connect, I receive:

There was a problem connecting to the server “172.16.16.1”.

Check the server name or IP address, and then try again. If you continue to have problems, contact your system administrator.
 
**To Reproduce**
1. Disable the host networking option and forward all ports specified in the read me.
2. Attempt to connect to the samba drive.

**Expected behavior**
Should be able to connect to the shared drive.

**How you're launching your container**

Using docker-compose:
```
  samba:
    image: mbentley/timemachine:smb
    container_name: samba
    restart: unless-stopped
    environment:
      - PASSWORD=redacted
      - SHARE_NAME="Backup"
    volumes:
      - /home/username/backup:/opt/timemachine
      - timemachine-var-lib-samba:/var/lib/samba
      - timemachine-var-cache-samba:/var/cache/samba
      - timemachine-run-samba:/run/samba
    ports:
      - 137:137/udp
      - 138:138/udp
      - 139:139
      - 445:445
```

**Container Logs**

Every time I attempt to connect, I see this in the container logs:
```
Failed to fetch record!
pcap cache not loaded
```

**Additional context**
