### ISSUE TITLE
Docker run works, but compose fails: Cannot connect lp_enum(steam,enum): value is not in enum_list!

### ISSUE THREAD

**Issue by iain17** [mbentley/docker-timemachine#115]
**Describe the bug**
First time trying to use this image on a Raspberry Pi 4B (Linux raspberrypi 5.10.103-v8+ #1530 SMP PREEMPT Tue Mar 8 13:06:35 GMT 2022 aarch64 GNU/Linux). When connecting to the timemachine I get a "Time Machine can’t connect to the backup disk." error.

Looking at the logs I see the following errors:
```
Server startup complete. Host name is raspberrypi.local. Local service cookie is 1823333269.
Service "raspberrypi" (/etc/avahi/services/smbd.service) successfully established.
lp_enum(steam,enum): value is not in enum_list!
value for fruit: metadata type unknown
make_connection_snum: SMB_VFS_CONNECT for service 'IPC$' at '/tmp' failed: No error information
lp_enum(steam,enum): value is not in enum_list!
value for fruit: metadata type unknown
make_connection_snum: SMB_VFS_CONNECT for service 'IPC$' at '/tmp' failed: No error information
```

**To Reproduce**
1. Setup docker with the below attached docker compose file. 
2. Create volume maps /mnt/storage/timemachine. 
3. chmod -R 777 /mnt/storage/timemachine. 

**Expected behavior**
A successful connection to my new time machine backup.

**How you're launching your container**
```yaml
version: '2'
volumes:
  timemachine-var-lib-samba:
  timemachine-run-samba:
services:
  timemachine:
    image: mbentley/timemachine:smb
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
    network_mode: host
    environment:
      - ADVERTISED_HOSTNAME=
      - CUSTOM_SMB_CONF=false
      - CUSTOM_USER=false
      - DEBUG_LEVEL=1
      - HIDE_SHARES=no
      - EXTERNAL_CONF=
      - MIMIC_MODEL=TimeCapsule8,119
      - TM_USERNAME=timemachine
      - TM_GROUPNAME=timemachine
      - TM_UID=1000
      - TM_GID=1000
      - PASSWORD=timemachine
      - SET_PERMISSIONS=true
      - SHARE_NAME=TimeMachine
      - SMB_INHERIT_PERMISSIONS=yes
      - SMB_NFS_ACES=yes
      - SMB_METADATA=steam
      - SMB_PORT=445
      - SMB_VFS_OBJECTS=acl_xattr fruit streams_xattr
      - VOLUME_SIZE_LIMIT=1 T
      - WORKGROUP=WORKGROUP
    volumes:
      - /mnt/storage/timemachine/opt:/opt
      - timemachine-var-lib-samba:/var/lib/samba
      - /mnt/ramdisk/samba:/var/cache/samba
      - timemachine-run-samba:/run/samba
```

**Container Logs**
```
Joining mDNS multicast group on interface br-5f75bbf9a917.IPv6 with address fe80::42:d6ff:fef9:7535.
New relevant interface br-5f75bbf9a917.IPv6 for mDNS.
Joining mDNS multicast group on interface br-5f75bbf9a917.IPv4 with address 172.20.0.1.
New relevant interface br-5f75bbf9a917.IPv4 for mDNS.
Joining mDNS multicast group on interface br-46023ec9c5ae.IPv4 with address 172.28.0.1.
New relevant interface br-46023ec9c5ae.IPv4 for mDNS.
Joining mDNS multicast group on interface br-45220c7fe0ed.IPv6 with address fe80::42:3aff:fe53:915a.
New relevant interface br-45220c7fe0ed.IPv6 for mDNS.
Joining mDNS multicast group on interface br-45220c7fe0ed.IPv4 with address 172.23.0.1.
New relevant interface br-45220c7fe0ed.IPv4 for mDNS.
Joining mDNS multicast group on interface eth0.IPv6 with address fe80::54d:d39:a8b1:7128.
New relevant interface eth0.IPv6 for mDNS.
Joining mDNS multicast group on interface eth0.IPv4 with address 192.168.0.25.
New relevant interface eth0.IPv4 for mDNS.
Joining mDNS multicast group on interface lo.IPv6 with address ::1.
New relevant interface lo.IPv6 for mDNS.
Joining mDNS multicast group on interface lo.IPv4 with address 127.0.0.1.
New relevant interface lo.IPv4 for mDNS.
Network interface enumeration completed.
Registering new address record for fe80::329:1d06:e0dd:d78f on vethc45c0e0.*.
Registering new address record for 169.254.158.218 on vethc45c0e0.IPv4.
Registering new address record for fe80::42:7cff:fe3c:7971 on br-dee2b2b98d4f.*.
Registering new address record for 172.18.0.1 on br-dee2b2b98d4f.IPv4.
Registering new address record for fe80::5c95:2eff:fe25:e740 on veth8871f14.*.
Registering new address record for 169.254.92.165 on veth8871f14.IPv4.
Registering new address record for fe80::a98:3c04:704a:eb on vethf1f3824.*.
Registering new address record for 169.254.111.17 on vethf1f3824.IPv4.
Registering new address record for fe80::d087:6fff:fee7:a48c on vethce29e00.*.
Registering new address record for 169.254.120.204 on vethce29e00.IPv4.
Registering new address record for fe80::42:82ff:febb:23ca on br-e9a746eb7edf.*.
Registering new address record for 172.24.0.1 on br-e9a746eb7edf.IPv4.
Registering new address record for fe80::42:91ff:fe8d:2b10 on docker0.*.
Registering new address record for 172.17.0.1 on docker0.IPv4.
Registering new address record for fe80::42:d6ff:fef9:7535 on br-5f75bbf9a917.*.
Registering new address record for 172.20.0.1 on br-5f75bbf9a917.IPv4.
Registering new address record for 172.28.0.1 on br-46023ec9c5ae.IPv4.
Registering new address record for fe80::42:3aff:fe53:915a on br-45220c7fe0ed.*.
Registering new address record for 172.23.0.1 on br-45220c7fe0ed.IPv4.
Registering new address record for fe80::54d:d39:a8b1:7128 on eth0.*.
Registering new address record for 192.168.0.25 on eth0.IPv4.
Registering new address record for ::1 on lo.*.
Registering new address record for 127.0.0.1 on lo.IPv4.
Server startup complete. Host name is raspberrypi.local. Local service cookie is 1823333269.
Service "raspberrypi" (/etc/avahi/services/smbd.service) successfully established.
lp_enum(steam,enum): value is not in enum_list!
value for fruit: metadata type unknown
make_connection_snum: SMB_VFS_CONNECT for service 'IPC$' at '/tmp' failed: No error information
lp_enum(steam,enum): value is not in enum_list!
value for fruit: metadata type unknown
make_connection_snum: SMB_VFS_CONNECT for service 'IPC$' at '/tmp' failed: No error information
*****

Samba name server RASPBERRYPI is now a local master browser for workgroup WORKGROUP on subnet 169.254.92.165

*****
*****

Samba name server RASPBERRYPI is now a local master browser for workgroup WORKGROUP on subnet 169.254.111.17

*****
*****

Samba name server RASPBERRYPI is now a local master browser for workgroup WORKGROUP on subnet 169.254.120.204

*****
*****

Samba name server RASPBERRYPI is now a local master browser for workgroup WORKGROUP on subnet 169.254.158.218

*****
*****

Samba name server RASPBERRYPI is now a local master browser for workgroup WORKGROUP on subnet 172.17.0.1

*****
*****

Samba name server RASPBERRYPI is now a local master browser for workgroup WORKGROUP on subnet 172.18.0.1

*****
*****

Samba name server RASPBERRYPI is now a local master browser for workgroup WORKGROUP on subnet 172.20.0.1

*****
*****

Samba name server RASPBERRYPI is now a local master browser for workgroup WORKGROUP on subnet 172.23.0.1

*****
*****

Samba name server RASPBERRYPI is now a local master browser for workgroup WORKGROUP on subnet 172.24.0.1

*****
*****

Samba name server RASPBERRYPI is now a local master browser for workgroup WORKGROUP on subnet 172.28.0.1

*****
```
