### ISSUE TITLE
Time machine gets connected but waits on `Locating backup drive...` and eventually errors out

### ISSUE THREAD

**Issue by vedhavyas** [mbentley/docker-timemachine#116]
**Describe the bug**

**To Reproduce**
Running with the following env
	 - TM_USERNAME=${SMB_USER}
      - PASSWORD=${SMB_PASS}
      - SET_PERMISSIONS=true
      - TM_UID=${PUID}
      - TM_GID=${PGID}
      - SMB_INHERIT_PERMISSIONS=yes
      - DEBUG_LEVEL=3
      - WORKGROUP=Hub

**Expected behavior**
Once connected, timemachine starts backing up

**How you're launching your container**
```
timemachine:
    image: mbentley/timemachine:smb
    container_name: timemachine
    environment:
      - TM_USERNAME=${SMB_USER}
      - PASSWORD=${SMB_PASS}
      - SET_PERMISSIONS=true
      - TM_UID=${PUID}
      - TM_GID=${PGID}
      - SMB_INHERIT_PERMISSIONS=yes
      - DEBUG_LEVEL=3
      - WORKGROUP=Hub
    restart: unless-stopped
    networks:
      docker-direct:
        ipv4_address: 10.10.2.253
    volumes:
      - ${HUB_DIR}/time-machine:/opt/timemachine
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
```

**Container Logs**

```
Registered MSG_REQ_POOL_USAGE
Allowed connection from 10.10.1.3 (10.10.1.3)
init_oplocks: initializing messages.
Transaction 0 of length 73 (0 toread)
switch message SMBnegprot (pid 66) conn 0x0
Requested protocol [NT LM 0.12]
Requested protocol [SMB 2.002]
Requested protocol [SMB 2.???]
Selected protocol SMB2_FF
GENSEC backend 'gssapi_spnego' registered
GENSEC backend 'gssapi_krb5' registered
GENSEC backend 'gssapi_krb5_sasl' registered
GENSEC backend 'spnego' registered
GENSEC backend 'schannel' registered
GENSEC backend 'naclrpc_as_system' registered
GENSEC backend 'sasl-EXTERNAL' registered
GENSEC backend 'ntlmssp' registered
GENSEC backend 'ntlmssp_resume_ccache' registered
GENSEC backend 'http_basic' registered
GENSEC backend 'http_ntlm' registered
GENSEC backend 'http_negotiate' registered
Selected protocol SMB 2.???
smbd_do_qfsinfo: level = 1003
Selected protocol SMB3_11
Allowed connection from 10.10.1.3 (10.10.1.3)
Selected protocol SMB3_11
Server exit (passed connection)
Registered MSG_REQ_POOL_USAGE
Allowed connection from 10.10.1.3 (10.10.1.3)
init_oplocks: initializing messages.
Transaction 0 of length 73 (0 toread)
switch message SMBnegprot (pid 67) conn 0x0
Requested protocol [NT LM 0.12]
Requested protocol [SMB 2.002]
Requested protocol [SMB 2.???]
Selected protocol SMB2_FF
GENSEC backend 'gssapi_spnego' registered
GENSEC backend 'gssapi_krb5' registered
GENSEC backend 'gssapi_krb5_sasl' registered
GENSEC backend 'spnego' registered
GENSEC backend 'schannel' registered
GENSEC backend 'naclrpc_as_system' registered
GENSEC backend 'sasl-EXTERNAL' registered
GENSEC backend 'ntlmssp' registered
GENSEC backend 'ntlmssp_resume_ccache' registered
GENSEC backend 'http_basic' registered
GENSEC backend 'http_ntlm' registered
GENSEC backend 'http_negotiate' registered
Selected protocol SMB 2.???
Selected protocol SMB3_11
Allowed connection from 10.10.1.3 (10.10.1.3)
Selected protocol SMB3_11
Server exit (passed connection)
smbd_do_qfsinfo: level = 1003
unix_mode(.) inherit mode 40770
unix_mode(.:AFP_AfpInfo) inherit mode 40770
smbd_smb2_request_error_ex: smbd_smb2_request_error_ex: idx[1] status[NT_STATUS_OBJECT_NAME_NOT_FOUND] || at ../../source3/smbd/smb2_create.c:337
smbd_smb2_request_error_ex: smbd_smb2_request_error_ex: idx[5] status[NT_STATUS_OBJECT_NAME_NOT_FOUND] || at ../../source3/smbd/smb2_server.c:3323
smbd_smb2_request_error_ex: smbd_smb2_request_error_ex: idx[9] status[NT_STATUS_OBJECT_NAME_NOT_FOUND] || at ../../source3/smbd/smb2_server.c:3323
smbd_do_qfsinfo: level = 1003
unix_mode(.) inherit mode 40770
unix_mode(.:AFP_AfpInfo) inherit mode 40770
smbd_smb2_request_error_ex: smbd_smb2_request_error_ex: idx[1] status[NT_STATUS_OBJECT_NAME_NOT_FOUND] || at ../../source3/smbd/smb2_create.c:337
smbd_smb2_request_error_ex: smbd_smb2_request_error_ex: idx[5] status[NT_STATUS_OBJECT_NAME_NOT_FOUND] || at ../../source3/smbd/smb2_server.c:3323
smbd_smb2_request_error_ex: smbd_smb2_request_error_ex: idx[9] status[NT_STATUS_OBJECT_NAME_NOT_FOUND] || at ../../source3/smbd/smb2_server.c:3323
send_local_master_announcement: type 849a03 for name 0E8441200715 on subnet 10.10.2.253 for workgroup HUB
send_workgroup_announcement: on subnet 10.10.2.253 for workgroup HUB
smbd_do_qfsinfo: level = 1003
unix_mode(.) inherit mode 40770
unix_mode(.:AFP_AfpInfo) inherit mode 40770
smbd_smb2_request_error_ex: smbd_smb2_request_error_ex: idx[1] status[NT_STATUS_OBJECT_NAME_NOT_FOUND] || at ../../source3/smbd/smb2_create.c:337
smbd_smb2_request_error_ex: smbd_smb2_request_error_ex: idx[5] status[NT_STATUS_OBJECT_NAME_NOT_FOUND] || at ../../source3/smbd/smb2_server.c:3323
smbd_smb2_request_error_ex: smbd_smb2_request_error_ex: idx[9] status[NT_STATUS_OBJECT_NAME_NOT_FOUND] || at ../../source3/smbd/smb2_server.c:3323
```

**Additional context**
