### ISSUE TITLE
Multiple Users: "/users" was not found

### ISSUE THREAD

**Issue by gbomacfly** [mbentley/docker-timemachine#117]
Hello,

I am trying to get multiple users working.
I have a external complete empty 4TB HDD, which is mounted to /mnt/TimeMachine in exFat
My config is in /opt/docker-compose/timemachine
In singleusermode it works as expected, but if I try multiple users, I get the following error:

```
/opt/docker-compose/timemachine $ docker-compose down && docker-compose up -d && docker logs -f timemachine
Stopping timemachine ... done
Removing timemachine ... done
Creating timemachine ... done
INFO: CUSTOM_SMB_CONF=false; generating [global] section of /etc/samba/smb.conf...
INFO: Creating /var/log/samba/cores
INFO: Avahi - generating base configuration in /etc/avahi/services/smbd.service...
INFO: Avahi - using "gboslave" as hostname.
ERROR: The value of EXTERNAL_CONF should be a directory mounted inside the container; "/users" was not found
```
But I don't get it, I mount the folder, which you can see in my docker-compose.yml:

```
version: '3'

services:

  timemachine:
    image: mbentley/timemachine:latest
    container_name: timemachine
    network_mode: "host"
    restart: unless-stopped
    environment:
      - ADVERTISED_HOSTNAME="gboslave"
      - CUSTOM_USER="false"
      - CUSTOM_SMB_CONF="false"
      - SET_PERMISSIONS="true"
      - WORKGROUP=“GBO”
      - DEBUG_LEVEL="1"
      - MIMIC_MODEL="TimeCapsule8,119"
      - EXTERNAL_CONF="/users"
      - HIDE_SHARES="no"
      - TM_UID="1000"
      - TM_GID="1000"
    volumes:
      - /mnt/TimeMachine/:/opt
      - ./userconf:/users
      - ./netatalk:/var/netatalk
      - ./logs:/var/log/supervisor
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
```
---
my config-folder:
```
$ tree /opt/docker-compose/timemachine
├── docker-compose.yml
├── logs
├── netatalk
└── userconf
    ├── macmini.conf
    └── mbp.conf
```
---
/opt/docker-compose/timemachine/userconf/macmini.conf:
```
TM_USERNAME=macmini
TM_GROUPNAME=gbo
PASSWORD=xxx
SHARE_NAME=macmini
VOLUME_SIZE_LIMIT="2 T"
TM_UID=1000
TM_GID=1000
```
---
/opt/docker-compose/timemachine/userconf/mbp.conf:
```
TM_USERNAME=mbp
TM_GROUPNAME=gbo
PASSWORD=xxx
SHARE_NAME=mbp
VOLUME_SIZE_LIMIT="2 T"
TM_UID=1000
TM_GID=1000
```

What am I doing wrong?
