### ISSUE TITLE
Permission issues

### ISSUE THREAD

**Issue by marcbria** [mbentley/docker-timemachine#14]
First, thanks for the project and to keep it open. 

I cloned locally your repo, then I modify timemachine variables (just the pwd and share_name) and run docker-compose, and the remote server is shown in my Macs, but when I select the server, I get this message:

`"You do not have the necessary read, write and append privileges on the selected network backup disk."`

I double-check permissions (/timemachine folder is owned by 1000 user and group) but I didn't find logs to report it better. The server is a ubuntu 19.04 with your docker and nothing else, and the client is a Mac with 10.6.8.

Any clue about what is happening?

Thanks for your time,
m.

**Comment by mbentley** [comment]
Could you provide the updated Docker compose file (without the password) so I can take a quick look?

**Comment by marcbria** [comment]
Sure. Here it is:

```
version: '3'
services:
  timemachine:
    network_mode: "host"
    environment:
      - CUSTOM_AFP_CONF=false
      - LOG_LEVEL=info
      - MIMIC_MODEL=TimeCapsule6,106
      - TM_USERNAME=timemachine
      - TM_GROUPNAME=timemachine
      - TM_UID=1000
      - TM_GID=1000
      - PASSWORD=xxxxx
      - SET_PERMISSIONS=false
      - SHARE_NAME=TimeMachineSP
      - VOLUME_SIZE_LIMIT=0
    restart: unless-stopped
    ports:
     - "548:548"
     - "636:636"
    volumes:
     - ./volumes/data:/timemachine
     - ./timemachine-netatalk:/var/netatalk
     - ./timemachine-logs:/var/log/supervisor
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    container_name: timemachine
    image: mbentley/timemachine:latest

```

As said, the only changes are PASSWORD, SHARE_NAME and also , the first volume (I usually place docker data in the same folder as "./volumes/data").

Thanks for your time,
m.
