### ISSUE TITLE
help deploy 2 containers

### ISSUE THREAD

**Issue by lbenicio** [mbentley/docker-timemachine#48]
Hi folks, im trying to deploy 2 container mapping each one to a external drive but I'm getting a lot of trouble with samba killing each other.

I'm trying a smb over a raspverry-pi 3b+

I'm always getting paid errors like these: (depending the deploy order and compose or not, the message varies a little bit)

```
s 1932735948.
Service "7e765b07e5bc" (/etc/avahi/services/smbd.service) successfully established.
Failed to fetch record!
pcap cache not loaded
===============================================================
INTERNAL ERROR: Signal 11 in pid 43 (4.12.2)
If you are running a recent Samba version, and if you think this problem is not yet fixed in the latest versions, please consider reporting this bug, see https://wiki.samba.org/index.php/Bug_Reporting
===============================================================
PANIC (pid 43): internal error
unable to produce a stack trace on this platform
dumping core in /var/log/samba/cores/smbd
*****

Samba name server 7E765B07E5BC is now a local master browser for workgroup WORKGROUP on subnet 192.168.86.248

*****
```

**Comment by mbentley** [comment]
Could you describe how you're deploying the containers?  You can't deploy two Samba containers on the same IP address so that could be part of it.

**Comment by lbenicio** [comment]
i tryed both methods, but now im using a compose file... a created a macvlan as described on README and then on compose a set a external network and o each container a assigned an different IP:

here is the compose

```
version: "3.7"
services:
  time_machine01:
    networks:
      macvlan1:
        ipv4_address: 192.168.86.248
    hostname: timecapsule01.local
    environment:
      - MIMIC_MODEL=TimeCapsule8,119
      - TM_USERNAME=user1
      - TM_GROUPNAME=user1
      - TM_UID=1000
      - TM_GID=1000
      - PASSWORD=pass1
      - SET_PERMISSIONS=true
      - SHARE_NAME=TimeMachin01
      - SMB_PORT=445
    restart: unless-stopped
    ports:
     - "137:137/udp"
     - "138:138/udp"
     - "139:139"
    volumes:
     - /tm/host/path:/opt/user1
     - timemachine-var-lib-samba:/var/lib/samba
     - timemachine-var-cache-samba:/var/cache/samba
     - timemachine-run-samba:/run/samba
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    container_name: time_machine_01
    image: mbentley/timemachine:smb-armv7l

  time_machine02:
    networks:
      macvlan1:
        ipv4_address: 192.168.86.249
    hostname: timecapsule02.local
    environment:
      - MIMIC_MODEL=TimeCapsule8,119
      - TM_USERNAME=user2
      - TM_GROUPNAME=user2
      - TM_UID=1000
      - TM_GID=1000
      - PASSWORD=pass2
      - SET_PERMISSIONS=true
      - SHARE_NAME=TimeMachin02
      - SMB_PORT=445
    restart: unless-stopped
    ports:
     - "137:137/udp"
     - "138:138/udp"
     - "139:139"
    volumes:
     - /host/path/tm:/opt/user2
     - timemachine-var-lib-samba:/var/lib/samba
     - timemachine-var-cache-samba:/var/cache/samba
     - timemachine-run-samba:/run/samba
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    container_name: time_machine_02
    image: mbentley/timemachine:smb-armv7l

networks:
  macvlan1:
    external: true

volumes:
  timemachine-var-lib-samba:
  timemachine-var-cache-samba:
  timemachine-run-samba:
```

when running like this I got error like these:

```
INFO: Profiling support unavailable in this build.
ERROR: smbd is already running. File /run/samba/smbd.pid exists and process id 35 is running.
nmbd version 4.12.2 started.
Copyright Andrew Tridgell and the Samba Team 1992-2020
pidfile_create: ERROR: Failed to create PID file /run/samba/nmbd.pid (Resource temporarily unavailable)
smbd version 4.12.2 started.
Copyright Andrew Tridgell and the Samba Team 1992-2020
INFO: Profiling support unavailable in this build.
ERROR: smbd is already running. File /run/samba/smbd.pid exists and process id 35 is running.
nmbd version 4.12.2 started.
Copyright Andrew Tridgell and the Samba Team 1992-2020
pidfile_create: ERROR: Failed to create PID file /run/samba/nmbd.pid (Resource temporarily unavailable)
smbd version 4.12.2 started.
Copyright Andrew Tridgell and the Samba Team 1992-2020
INFO: Profiling support unavailable in this build.
ERROR: smbd is already running. File /run/samba/smbd.pid exists and process id 35 is running.
```

**Comment by undaunt** [comment]
I'm not an expert, but I'm pretty sure you need your second container to use different ports. Eg, do this:

```
version: "3.7"
services:
  time_machine01:
    ports:
     - "137:137/udp"
     - "138:138/udp"
     - "139:139"

  time_machine02:
    ports:
     - "1137:137/udp"
     - "1138:138/udp"
     - "1139:139"
```

You may need to do similar with the volumes. I don't know.
