### ISSUE TITLE
Macvlan Server Name

### ISSUE THREAD

**Issue by undaunt** [mbentley/docker-timemachine#51]
Hey,

Just wondering how it would be possible to name the share parent (ie: the 'server' not the share itself) when using macvlan?

If I create a share via host networking, I get the name of my server, then the share 'TimeMachine' inside. However, when swapping to macvlan, the server name is instead named the first 12 characters of the container ID.

Eg: Portainer lists my timemachine container ID as:

56c926ac15afd0becd4e23cdf33cc0b3d536a9b9e1a0d74d62fed734904425f2

So the share is coming up as 56c926ac15af.local instead of 'server-name.local'. This doesn't appear to change even when using the 'name' function in docker compose.

```
  timeMachine:
    ipam:
      config:
        - subnet: 192.168.60.0/24
    name: timeMachine
    driver: macvlan
    driver_opts:
      com.docker.network.bridge.name: timeMachine
      parent: ens18
```

Thank you.
