### ISSUE TITLE
Macvlan Connectivity

### ISSUE THREAD

**Issue by undaunt** [mbentley/docker-timemachine#52]
Hey Matt,

I'm so close to getting this working with macvlan. I'm able to see the share, but unlike with host networking I cannot connect to it successfully, it eventually just times out. Here's my logs and my compose with debugging turned up. Please let me know if anything jumps out.

I have a host level SMB service set up as this is running on my NAS system, so I had to adjust the external container ports. Not sure if that's the issue. Thanks!

```
today at 6:23 PM INFO: CUSTOM_SMB_CONF=false; generating [global] section of /etc/samba/smb.conf...
today at 6:23 PM Creating /var/log/samba/cores
today at 6:23 PM INFO: Avahi - generating base configuration in /etc/avahi/services/smbd.service...
today at 6:23 PM INFO: Avahi - adding the 'dk0', 'TimeMachine' share txt-record to /etc/avahi/services/smbd.service...
today at 6:23 PM INFO: Group timemachine doesn't exist; creating...
today at 6:23 PM INFO: User timemachine doesn't exist; creating...
today at 6:23 PM INFO: Using default password: timemachine
today at 6:23 PM chpasswd: password for 'timemachine' changed
today at 6:23 PM INFO: INFO: CUSTOM_SMB_CONF=false; generating [TimeMachine] section of /etc/samba/smb.conf...
today at 6:23 PM INFO: Samba - Created Added user timemachine.
today at 6:23 PM INFO: Samba - Enabled user timemachine.
today at 6:23 PM INFO: Samba - setting password
today at 6:23 PM INFO: SET_PERMISSIONS=false; not setting ownership and permissions for /opt/timemachine
today at 6:23 PM INFO: Avahi - completing the configuration in /etc/avahi/services/smbd.service...
today at 6:23 PM INFO: smbd PID exists; removing...
today at 6:23 PM removed '/run/samba/smbd.pid'
today at 6:23 PM INFO: entrypoint complete; executing 's6-svscan /etc/s6'
today at 6:23 PM dbus socket not yet available; sleeping...
today at 6:23 PM nmbd version 4.12.2 started.
today at 6:23 PM Copyright Andrew Tridgell and the Samba Team 1992-2020
today at 6:23 PM lp_load_ex: refreshing parameters
today at 6:23 PM Initialising global parameters
today at 6:23 PM Processing section "[global]"
today at 6:23 PM Registered MSG_REQ_POOL_USAGE
today at 6:23 PM Registered MSG_REQ_DMALLOC_MARK and LOG_CHANGED
today at 6:23 PM lp_load_ex: refreshing parameters
today at 6:23 PM Initialising global parameters
today at 6:23 PM Processing section "[global]"
today at 6:23 PM services not loaded
today at 6:23 PM standard input is not a socket, assuming -D option
today at 6:23 PM Becoming a daemon.
today at 6:23 PM Registered MSG_REQ_POOL_USAGE
today at 6:23 PM Opening sockets 137
today at 6:23 PM open_sockets: Broadcast sockets opened.
today at 6:23 PM added interface eth0 ip=192.168.60.100 bcast=192.168.60.255 netmask=255.255.255.0
today at 6:23 PM making subnet name:192.168.60.100 Broadcast address:192.168.60.255 Subnet mask:255.255.255.0
today at 6:23 PM making subnet name:UNICAST_SUBNET Broadcast address:0.0.0.0 Subnet mask:0.0.0.0
today at 6:23 PM making subnet name:REMOTE_BROADCAST_SUBNET Broadcast address:0.0.0.0 Subnet mask:0.0.0.0
today at 6:23 PM Loaded hosts file /etc/samba/lmhosts
today at 6:23 PM add_name_to_subnet: Added netbios name *<00> with first IP 192.168.60.100 ttl=0 nb_flags= 0 to subnet 192.168.60.100
today at 6:23 PM add_name_to_subnet: Added netbios name *<20> with first IP 192.168.60.100 ttl=0 nb_flags= 0 to subnet 192.168.60.100
today at 6:23 PM add_name_to_subnet: Added netbios name __SAMBA__<20> with first IP 192.168.60.100 ttl=0 nb_flags= 0 to subnet 192.168.60.100
today at 6:23 PM add_name_to_subnet: Added netbios name __SAMBA__<00> with first IP 192.168.60.100 ttl=0 nb_flags= 0 to subnet 192.168.60.100
today at 6:23 PM create_server_on_workgroup: Created server entry TIMEMACHINE of type 40819a03 (Samba 4.12.2) on workgroup WORKGROUP.
today at 6:23 PM initiate_myworkgroup_startup: Added server name entry TIMEMACHINE on subnet 192.168.60.100
today at 6:23 PM add_name_to_subnet: Added netbios name *<00> with first IP 192.168.60.100 ttl=0 nb_flags= 0 to subnet UNICAST_SUBNET
today at 6:23 PM add_name_to_subnet: Added netbios name *<20> with first IP 192.168.60.100 ttl=0 nb_flags= 0 to subnet UNICAST_SUBNET
today at 6:23 PM add_name_to_subnet: Added netbios name __SAMBA__<20> with first IP 192.168.60.100 ttl=0 nb_flags= 0 to subnet UNICAST_SUBNET
today at 6:23 PM add_name_to_subnet: Added netbios name __SAMBA__<00> with first IP 192.168.60.100 ttl=0 nb_flags= 0 to subnet UNICAST_SUBNET
today at 6:23 PM add_name_to_subnet: Added netbios name TIMEMACHINE<20> with first IP 192.168.60.100 ttl=0 nb_flags= 0 to subnet UNICAST_SUBNET
today at 6:23 PM add_name_to_subnet: Added netbios name TIMEMACHINE<03> with first IP 192.168.60.100 ttl=0 nb_flags= 0 to subnet UNICAST_SUBNET
today at 6:23 PM add_name_to_subnet: Added netbios name TIMEMACHINE<00> with first IP 192.168.60.100 ttl=0 nb_flags= 0 to subnet UNICAST_SUBNET
today at 6:23 PM add_name_to_subnet: Added netbios name WORKGROUP<00> with first IP 192.168.60.100 ttl=0 nb_flags=80 to subnet UNICAST_SUBNET
today at 6:23 PM add_name_to_subnet: Added netbios name WORKGROUP<1e> with first IP 192.168.60.100 ttl=0 nb_flags=80 to subnet UNICAST_SUBNET
today at 6:23 PM add_name_to_subnet: Added netbios name *<00> with first IP 192.168.60.100 ttl=0 nb_flags= 0 to subnet REMOTE_BROADCAST_SUBNET
today at 6:23 PM add_name_to_subnet: Added netbios name *<20> with first IP 192.168.60.100 ttl=0 nb_flags= 0 to subnet REMOTE_BROADCAST_SUBNET
today at 6:23 PM add_name_to_subnet: Added netbios name __SAMBA__<20> with first IP 192.168.60.100 ttl=0 nb_flags= 0 to subnet REMOTE_BROADCAST_SUBNET
today at 6:23 PM add_name_to_subnet: Added netbios name __SAMBA__<00> with first IP 192.168.60.100 ttl=0 nb_flags= 0 to subnet REMOTE_BROADCAST_SUBNET
today at 6:23 PM daemon_ready: daemon 'nmbd' finished starting up and ready to serve connections
today at 6:23 PM send_host_announcement: type 819a03 for host TIMEMACHINE on subnet 192.168.60.100 for workgroup WORKGROUP
today at 6:23 PM smbd version 4.12.2 started.
today at 6:23 PM Copyright Andrew Tridgell and the Samba Team 1992-2020
today at 6:23 PM uid=0 gid=0 euid=0 egid=0
today at 6:23 PM lp_load_ex: refreshing parameters
today at 6:23 PM Initialising global parameters
today at 6:23 PM Processing section "[global]"
today at 6:23 PM Registered MSG_REQ_POOL_USAGE
today at 6:23 PM Registered MSG_REQ_DMALLOC_MARK and LOG_CHANGED
today at 6:23 PM lp_load_ex: refreshing parameters
today at 6:23 PM Initialising global parameters
today at 6:23 PM Processing section "[global]"
today at 6:23 PM Processing section "[TimeMachine]"
today at 6:23 PM adding IPC service
today at 6:23 PM added interface eth0 ip=192.168.60.100 bcast=192.168.60.255 netmask=255.255.255.0
today at 6:23 PM loaded services
today at 6:23 PM INFO: Profiling support unavailable in this build.
today at 6:23 PM Standard input is not a socket, assuming -D option
today at 6:23 PM Becoming a daemon.
today at 6:23 PM Registered MSG_REQ_POOL_USAGE
today at 6:23 PM No builtin backend found, trying to load plugin
today at 6:23 PM load_module_absolute_path: Module '/usr/lib/samba/pdb/tdbsam.so' loaded
today at 6:23 PM pid_to_procid: messaging_dgm_get_unique failed: No such file or directory
today at 6:23 PM Registered MSG_REQ_POOL_USAGE
today at 6:23 PM Registered MSG_REQ_POOL_USAGE
today at 6:23 PM Failed to fetch domain sid for WORKGROUP
today at 6:23 PM Initialise the svcctl registry keys if needed.
today at 6:23 PM Initialise the eventlog registry keys if needed.
today at 6:23 PM register_rpc_module: Successfully added RPC module 'mdssvc'
today at 6:23 PM daemon_ready: daemon 'smbd' finished starting up and ready to serve connections
today at 6:23 PM start_background_queue: Starting background LPQ thread
today at 6:23 PM Failed to fetch record!
today at 6:23 PM waiting for connections
today at 6:23 PM Registered MSG_REQ_POOL_USAGE
today at 6:23 PM reloading printcap cache
today at 6:23 PM pcap_cache_reload: skipping reload - load printers disabled
today at 6:23 PM Found user 'avahi' (UID 86) and group 'avahi' (GID 86).
today at 6:23 PM Successfully dropped root privileges.
today at 6:23 PM avahi-daemon 0.8 starting up.
today at 6:23 PM WARNING: No NSS support for mDNS detected, consider installing nss-mdns!
today at 6:23 PM Loading service file /etc/avahi/services/smbd.service.
today at 6:23 PM Joining mDNS multicast group on interface eth0.IPv4 with address 192.168.60.100.
today at 6:23 PM New relevant interface eth0.IPv4 for mDNS.
today at 6:23 PM Joining mDNS multicast group on interface lo.IPv4 with address 127.0.0.1.
today at 6:23 PM New relevant interface lo.IPv4 for mDNS.
today at 6:23 PM Network interface enumeration completed.
today at 6:23 PM Registering new address record for 192.168.60.100 on eth0.IPv4.
today at 6:23 PM Registering new address record for 127.0.0.1 on lo.IPv4.
today at 6:23 PM Server startup complete. Host name is TimeMachine.local. Local service cookie is 1456743550.
today at 6:23 PM Service "TimeMachine" (/etc/avahi/services/smbd.service) successfully established.
today at 6:23 PM add_name_to_subnet: Added netbios name TIMEMACHINE<20> with first IP 192.168.60.100 ttl=0 nb_flags= 0 to subnet 192.168.60.100
today at 6:23 PM add_name_to_subnet: Added netbios name TIMEMACHINE<03> with first IP 192.168.60.100 ttl=0 nb_flags= 0 to subnet 192.168.60.100
today at 6:23 PM add_name_to_subnet: Added netbios name TIMEMACHINE<00> with first IP 192.168.60.100 ttl=0 nb_flags= 0 to subnet 192.168.60.100
today at 6:23 PM add_name_to_subnet: Added netbios name WORKGROUP<00> with first IP 192.168.60.100 ttl=0 nb_flags=80 to subnet 192.168.60.100
today at 6:23 PM add_name_to_subnet: Added netbios name WORKGROUP<1e> with first IP 192.168.60.100 ttl=0 nb_flags=80 to subnet 192.168.60.100
today at 6:23 PM check_for_master_browser_fail: Forcing election on workgroup WORKGROUP subnet 192.168.60.100
today at 6:23 PM check_elections: >>> Starting election for workgroup WORKGROUP on subnet 192.168.60.100 <<<
today at 6:23 PM write_browse_list: Wrote browse list into file /var/cache/samba/browse.dat
today at 6:23 PM send_election_dgram: Sending election packet for workgroup WORKGROUP on subnet 192.168.60.100
```

```
  timemachine:
    image: mbentley/timemachine:smb
    container_name: timemachine
    hostname: TimeMachine
    restart: unless-stopped
    networks:
      timeMachine:
        ipv4_address: 192.168.60.100
    ports:
      - "1137:137/udp"
      - "1138:138/udp"
      - "1139:139"
      - "446:445"
    volumes:
      - /mnt/zfs/data/timemachine:/opt/timemachine
      - timemachine-var-lib-samba:/var/lib/samba
      - timemachine-var-cache-samba:/var/cache/samba
      - timemachine-run-samba:/run/samba
    environment:
      - CUSTOM_SMB_CONF=false
      - CUSTOM_USER=false
      - LOG_LEVEL=info
      - EXTERNAL_CONF=
      - HIDE_SHARES=no
      - MIMIC_MODEL=TimeCapsule8,119
      - TM_USERNAME=timemachine
      - TM_GROUPNAME=timemachine
      - TM_UID=1000
      - TM_GID=1000
      - PASSWORD=timemachine
      - SET_PERMISSIONS=false
      - SHARE_NAME=TimeMachine
      - SMB_PORT=445
      - VOLUME_SIZE_LIMIT=0
      - WORKGROUP=WORKGROUP
      - DEBUG_LEVEL=3
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
```

```
  timeMachine:
    ipam:
      config:
        - subnet: 192.168.60.0/24
    name: timeMachine
    driver: macvlan
    driver_opts:
      com.docker.network.bridge.name: timeMachine
      parent: ens18
```
