### ISSUE TITLE
Couldn't start timemachine with Samba

### ISSUE THREAD

**Issue by evilangel-ru** [mbentley/docker-timemachine#54]
Hello.

I try to start the container with docker-compose file from the repository `timemachine-compose-smb.yml`. Just changed the path to the share on the host, rename it to docker-compose.yml and start it `docker-compose up -d`, but got an error:
`ERROR: Named volume "timemachine-var-lib-samba:/var/lib/samba:rw" is used in service "timemachine" but no declaration was found in the volumes section.`

Could somebody help me to understand what is wrong here?

**Comment by thewinger** [comment]
I'm also receiving this message.
I'm using docker-compose with the following text:

```
timemachine:
    image: mbentley/timemachine:smb
    container_name: timemachine
    restart: unless-stopped
    network_mode: host
    volumes:
       - $TIMEMACHINEDIR:/opt/timemachine
       - timemachine-var-lib-samba:/var/lib/samba
       - timemachine-var-cache-samba:/var/cache/samba
       - timemachine-run-samba:/run/samba
     environment:
       - TM_UID=$PUID
       - TM_GID=$PGID
       - VOLUME_SIZE_LIMIT="1 T"
       - SMB_PORT=11000
```
