### ISSUE TITLE
VOLUME_SIZE_LIMIT not being established

### ISSUE THREAD

**Issue by thewinger** [mbentley/docker-timemachine#63]
Everything looks fine but time machine preferences show the whole 8TB instead of the VOLUME_SIZE_LIMIT="1 T" that I set in the docker-compose file.

**Comment by mbentley** [comment]
Could you provide your compose file with any sensitive data redacted?

**Comment by mbentley** [comment]
It would also be good to provide the `smb.conf` that is generated like so assuming that `timemachine` is the name of the container; for example:

```
# docker exec -it timemachine cat /etc/samba/smb.conf
[global]
   min protocol = SMB2
   server role = standalone server
   workgroup = timemachine
   smb ports = 445
   #unix password sync = yes
   log file = /var/log/samba/log.%m
   logging = file
   max log size = 1000
   security = user
   load printers = no
   access based share enum = no
   hide unreadable = no
   vfs objects = fruit streams_xattr
   fruit:delete_empty_adfiles = yes
   fruit:metadata = stream
   fruit:model = TimeCapsule8,119
   fruit:posix_rename = yes
   fruit:veto_appledouble = no
   fruit:wipe_intentionally_left_blank_rfork = yes

[TimeMachine]
   fruit:aapl = yes
   fruit:time machine = yes
   fruit:time machine max size = 1 T
   path = /opt/timemachine
   valid users = timemachine
   browseable = yes
   writable = yes
   vfs objects = fruit streams_xattr
```

**Comment by thewinger** [comment]
docker-compose.yml
```
   timemachine:
     image: mbentley/timemachine:smb
     container_name: timemachine
     restart: unless-stopped
     network_mode: host
     volumes:
       - $TIMEMACHINEDIR:/opt/timemachine
       - timemachine-var-lib-samba:/var/lib/samba:rw
       - timemachine-var-cache-samba:/var/cache/samba
       - timemachine-run-samba:/run/samba
     environment:
       - TM_UID=$PUID
       - TM_GID=$PGID
       - VOLUME_SIZE_LIMIT="1 T"
       - SMB_PORT=11000

volumes:
   timemachine-var-lib-samba:
   timemachine-var-cache-samba:
   timemachine-run-samba:
```

cat of smb.conf
```
[global]
   min protocol = SMB2
   server role = standalone server
   workgroup = WORKGROUP
   smb ports = 11000
   #unix password sync = yes
   log file = /var/log/samba/log.%m
   logging = file
   max log size = 1000
   security = user
   load printers = no
   access based share enum = no
   hide unreadable = no
   vfs objects = fruit streams_xattr
   fruit:delete_empty_adfiles = yes
   fruit:metadata = stream
   fruit:model = TimeCapsule8,119
   fruit:posix_rename = yes
   fruit:veto_appledouble = no
   fruit:wipe_intentionally_left_blank_rfork = yes

[TimeMachine]
   fruit:aapl = yes
   fruit:time machine = yes
   fruit:time machine max size = "1 T"
   path = /opt/timemachine
   valid users = timemachine
   browseable = yes
   writable = yes
   vfs objects = fruit streams_xattr
```
