### ISSUE TITLE
Volumes ran full - maybe add a warning to compose, that /tmp should hold heaps of free disk space

### ISSUE THREAD

**Issue by totti4ever** [mbentley/docker-timemachine#71]
It was a big problem for me at least as I have my tmp on a SSD which doesn't hold too much of free space (like 30 GB), which was fine so far until this timemachine image filled it completely up :-)

**Comment by mbentley** [comment]
Are you saying /tmp on your host filled up because of time machine or in the container?  Does it only fill up when it's doing a backup or do files stick around?

**Comment by totti4ever** [comment]
On my host, must have been in one of the docker volumes.
Backup was running

**Comment by mbentley** [comment]
The reason I ask is that unless you have a container's volume mounted to /tmp on the host, it should not be possible for the container to impact /tmp on the host.

**Comment by totti4ever** [comment]
Okay, sorry. Have some further insights as it happened again.

Of course it is not the /tmp folder, sorry. It was the var folder or better the docker overlay, so none of the mapped folders (I switched them to mapped directories instead of volumes). So it is the container itself which gets this big during the backup.

Do you propose to map the /tmp folder of the container to some place on a hdd with a lot of space?

**Comment by mbentley** [comment]
Ah, ok, that is just because you're not mapping the volume to somewhere on the host with enough storage.  If you provided a sanitized version of your command to run the container, it would help.

**Comment by totti4ever** [comment]
I'd reckon my problem is this, which means the whole backup had been written into the container and not on disk, right? o_O
```
    environment:
      - TM_USERNAME=samba_me_time_backup
    volumes:
     - /datapool1/backup/me_time_backup_mac:/opt/timemachine
```

I switched it to
`     - /datapool1/backup/me_time_backup_mac:/opt/samba_me_time_backup`
This should work now, right?


----

```
version: "3.7"

services:

  timemachine:
    container_name: timemachine
    image: mbentley/timemachine:smb
    restart: unless-stopped
    # network_mode: "host"
    networks:
      timemachine:
        ipv4_address: '192.168.192.101'
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    ports:
     - "137:137/udp"
     - "138:138/udp"
     - "139:139"
    environment:
      - CUSTOM_SMB_CONF=false
      - CUSTOM_USER=false
      - LOG_LEVEL=info
      - EXTERNAL_CONF=
      - HIDE_SHARES=no
      - MIMIC_MODEL=TimeCapsule8,119
      - TM_USERNAME=samba_me_time_backup
      - TM_GROUPNAME=samba_me_time_backup
      - TM_UID=1003 # samba_me_time_backup
      - TM_GID=1007 # samba_me_time_backup
      - PASSWORD=6..................9
      - SET_PERMISSIONS=true
      - SHARE_NAME=TimeMachine
      - SMB_PORT=445
      - VOLUME_SIZE_LIMIT=350G
      - WORKGROUP=WORKGROUP


    volumes:
     - /datapool1/backup/me_time_backup_mac:/opt/timemachine
     - ./data/timemachine-var-lib-samba:/var/lib/samba
     - ./data/timemachine-var-cache-samba:/var/cache/samba
     - ./data/timemachine-run-samba:/run/samba


networks:
  timemachine:
    external: true

```
