### ISSUE TITLE
macOS Big Sur finder hangs sometimes

### ISSUE THREAD

**Issue by sterid** [mbentley/docker-timemachine#79]
I configured timemachine docker image on Ubuntu 20.04 VM (hyper-v) with 2Tb drive
```
timemachine:
  image: mbentley/timemachine
  container_name: timemachine
  environment: 
    PASSWORD: P@ssw0rd
    TM_USERNAME: timemachine
    TM_GROUPNAME: timemachine
    TM_UID: 1000
    TM_GID: 1000
    SHARE_NAME: "Time Machine"
  volumes:
    - /mnt/timecapsule1/macbookbackup:/opt/timemachine
  network_mode: host
  restart: always
```

Sometimes when I open Finder it hangs for 5-15 sec. It happens only when timemachine container works. 
I suppose finder connects to network drive at this time.
![image](https://user-images.githubusercontent.com/22502995/106244204-a5c93c80-621b-11eb-86c9-fdf7e080eba6.png)
When 'Time Machine' share appears in finder it become ok. Very annoying because I can't use finder for those 15 second every time.

How can it be fixed?
