### ISSUE TITLE
Can't backup to mounted SMB/CIFS share

### ISSUE THREAD

**Issue by tigattack** [mbentley/docker-timemachine#84]
**Describe the bug**
I've mounted a CIFS share on the host with UID and GUID 1000. Ii've confirmed R/W access from both the host and the container, however, when I attempt to run a TM backup from my Mac, it fails with this error:  
`The backup disk image could not be created.`

**To Reproduce**
1. Mount CIFS share on host as described.
2. Map to container as volume.
3. Attempt to run backup.
4. See error.

**Expected behavior**
I'd expect the backup to run successfully.

**How you're launching your container**
```YML
version: '3.3'
services:
    timemachine:
        image: 'mbentley/timemachine:smb'
        restart: unless-stopped
        container_name: timemachine
        network_mode: host
        environment:
            - CUSTOM_SMB_CONF=false
            - CUSTOM_USER=false
            - DEBUG_LEVEL=1
            - 'MIMIC_MODEL=TimeCapsule8,119'
            - EXTERNAL_CONF=
            - HIDE_SHARES=no
            - TM_USERNAME=timemachine
            - TM_GROUPNAME=timemachine
            - TM_UID=1000
            - TM_GID=1000
            - PASSWORD=/redacted/
            - SET_PERMISSIONS=false
            - SMB_INHERIT_PERMISSIONS=true
            - SHARE_NAME=TimeMachine
            - SMB_PORT=445
            - VOLUME_SIZE_LIMIT='1 T'
            - WORKGROUP=WORKGROUP
        volumes:
            - '/mnt/timemachine:/opt/timemachine'
            - 'timemachine-var-lib-samba:/var/lib/samba'
            - 'timemachine-var-cache-samba:/var/cache/samba'
            - 'timemachine-run-samba:/run/samba'

volumes:
    timemachine-var-lib-samba:
    timemachine-var-cache-samba:
    timemachine-run-samba:
```

**Container Logs**

The errors can be seen on the last two lines.
```
timemachine    | INFO: CUSTOM_SMB_CONF=false; generating [global] section of /etc/samba/smb.conf...
timemachine    | INFO: Creating /var/log/samba/cores
timemachine    | INFO: Avahi - generating base configuration in /etc/avahi/services/smbd.service...
timemachine    | INFO: Avahi - adding the 'dk0', 'TimeMachine' share txt-record to /etc/avahi/services/smbd.service...
timemachine    | INFO: Group timemachine doesn't exist; creating...
timemachine    | INFO: User timemachine doesn't exist; creating...
timemachine    | INFO: Setting password from environment variable
timemachine    | chpasswd: password for 'timemachine' changed
timemachine    | INFO: INFO: CUSTOM_SMB_CONF=false; generating [TimeMachine] section of /etc/samba/smb.conf...
timemachine    | INFO: Samba - Created User timemachine password set to none.
timemachine    | INFO: Samba - Enabled user timemachine.
timemachine    | INFO: Samba - setting password
timemachine    | INFO: SET_PERMISSIONS=false; not setting ownership and permissions for /opt/timemachine
timemachine    | INFO: Avahi - completing the configuration in /etc/avahi/services/smbd.service...
timemachine    | INFO: entrypoint complete; executing 's6-svscan /etc/s6'
timemachine    | dbus socket not yet available; sleeping...
timemachine    | nmbd version 4.12.9 started.
timemachine    | Copyright Andrew Tridgell and the Samba Team 1992-2020
timemachine    | daemon_ready: daemon 'nmbd' finished starting up and ready to serve connections
timemachine    | smbd version 4.12.9 started.
timemachine    | Copyright Andrew Tridgell and the Samba Team 1992-2020
timemachine    | INFO: Profiling support unavailable in this build.
timemachine    | daemon_ready: daemon 'smbd' finished starting up and ready to serve connections
timemachine    | Failed to fetch record!
timemachine    | Found user 'avahi' (UID 86) and group 'avahi' (GID 86).
timemachine    | Successfully dropped root privileges.
timemachine    | avahi-daemon 0.8 starting up.
timemachine    | WARNING: No NSS support for mDNS detected, consider installing nss-mdns!
timemachine    | Loading service file /etc/avahi/services/smbd.service.
timemachine    | Joining mDNS multicast group on interface docker0.IPv4 with address 172.17.0.1.
timemachine    | New relevant interface docker0.IPv4 for mDNS.
timemachine    | Joining mDNS multicast group on interface br-76137d576db5.IPv4 with address 172.21.0.1.
timemachine    | New relevant interface br-76137d576db5.IPv4 for mDNS.
timemachine    | Joining mDNS multicast group on interface ens160.IPv6 with address fe80::250:56ff:fe9a:1bf6.
timemachine    | New relevant interface ens160.IPv6 for mDNS.
timemachine    | Joining mDNS multicast group on interface ens160.IPv4 with address 10.52.0.35.
timemachine    | New relevant interface ens160.IPv4 for mDNS.
timemachine    | Joining mDNS multicast group on interface lo.IPv6 with address ::1.
timemachine    | New relevant interface lo.IPv6 for mDNS.
timemachine    | Joining mDNS multicast group on interface lo.IPv4 with address 127.0.0.1.
timemachine    | New relevant interface lo.IPv4 for mDNS.
timemachine    | Network interface enumeration completed.
timemachine    | Registering new address record for 172.17.0.1 on docker0.IPv4.
timemachine    | Registering new address record for 172.21.0.1 on br-76137d576db5.IPv4.
timemachine    | Registering new address record for fe80::250:56ff:fe9a:1bf6 on ens160.*.
timemachine    | Registering new address record for 10.52.0.35 on ens160.IPv4.
timemachine    | Registering new address record for ::1 on lo.*.
timemachine    | Registering new address record for 127.0.0.1 on lo.IPv4.
timemachine    | Server startup complete. Host name is Docker02.local. Local service cookie is 3782400960.
timemachine    | Service "Docker02" (/etc/avahi/services/smbd.service) successfully established.
timemachine    | *****
timemachine    |
timemachine    | Samba name server DOCKER02 is now a local master browser for workgroup WORKGROUP on subnet 172.21.0.1
timemachine    |
timemachine    | *****
timemachine    | *****
timemachine    |
timemachine    | Samba name server DOCKER02 is now a local master browser for workgroup WORKGROUP on subnet 10.52.0.35
timemachine    |
timemachine    | *****
timemachine    | *****
timemachine    |
timemachine    | Samba name server DOCKER02 is now a local master browser for workgroup WORKGROUP on subnet 172.17.0.1
timemachine    |
timemachine    | *****
timemachine    | fruit_pread_meta_stream: Removing [B8600E50-E9F6-53BA-918A-754816B77916.sparsebundle:AFP_AfpInfo] after short read [0]
timemachine    | fruit_pwrite_meta_stream: On-demand create [B8600E50-E9F6-53BA-918A-754816B77916.sparsebundle:AFP_AfpInfo] in write failed: Invalid argument
```

**Additional context**
```
$ docker exec -it timemachine /bin/sh
/ # cd /opt/timemachine/
/opt/timemachine # ls -lah
total 12K
drwxr-xr-x    2 timemach timemach       0 Mar 27 13:57 .
drwxr-xr-x    1 root     root        4.0K Mar 27 13:51 ..
-rwxr-xr-x    1 timemach timemach    6.0K Mar 27 12:37 .DS_Store
/opt/timemachine # touch testFile
/opt/timemachine # ls -lah
total 12K
drwxr-xr-x    2 timemach timemach       0 Mar 27 13:58 .
drwxr-xr-x    1 root     root        4.0K Mar 27 13:51 ..
-rwxr-xr-x    1 timemach timemach    6.0K Mar 27 12:37 .DS_Store
-rwxr-xr-x    1 timemach timemach       0 Mar 27 13:58 testFile
/opt/timemachine # rm testFile
/opt/timemachine # ls -lah
total 12K
drwxr-xr-x    2 timemach timemach       0 Mar 27 13:58 .
drwxr-xr-x    1 root     root        4.0K Mar 27 13:51 ..
-rwxr-xr-x    1 timemach timemach    6.0K Mar 27 12:37 .DS_Store
```
