### ISSUE TITLE
Backing up is extremely slow

### ISSUE THREAD

**Issue by DarthSmeg** [mbentley/docker-timemachine#90]
**Describe the bug**
Doing my initial backup of 1,5TB took almost a week. A daily incremental of a few hundred megs still take hours. Running ftp-transfers between the same machines easily reach speeds of 30+ MB/s, while the timemachine speeds are less than 1.

**To Reproduce**
1. spin up the container
2. start the backup
3. wait
4. wait some more :)

**Expected behavior**

Faster backups

**How you're launching your container**

```
Running from compose. I have experimented with a few different fruit settings but haven't achieved much.
  timemachine:
    container_name: timemachine
    image: mbentley/timemachine:smb
    network_mode: host
    environment:
      - CUSTOM_SMB_CONF=false
      - CUSTOM_USER=false
      - DEBUG_LEVEL=1
      - HIDE_SHARES=no
      - EXTERNAL_CONF=""
      - 'MIMIC_MODEL=TimeCapsule8,119'
      - TM_USERNAME=timemachine
      - TM_GROUPNAME=timemachine
      - TM_UID=${PUID}
      - TM_GID=${PGID}
      - PASSWORD=${TM_PASSWORD}
      - SET_PERMISSIONS=false
      - SHARE_NAME=TimeMachine
      - SMB_INHERIT_PERMISSIONS=no
      - SMB_NFS_ACES=yes
      - SMB_PORT=445
      - 'SMB_VFS_OBJECTS=catia fruit streams_xattr acl_xattr'
      - 'VOLUME_SIZE_LIMIT=2 T'
      - WORKGROUP=WORKGROUP
    restart: unless-stopped
    volumes:
      - ${TIMEMACHINEDIR}:/opt/timemachine
      - ${USERDIR}/samba/timemachine-var-lib-samba:/var/lib/samba
      - ${USERDIR}/samba/timemachine-var-cache-samba:/var/cache/samba
      - ${USERDIR}/samba/timemachine-run-samba:/run/samba
```

**Container Logs**

```
there aren't really any errors, just hoping for pointers to improve my situation.
```

**Additional context**

I found a guide to improve SMB performance for the mac, and applied some of those to the client. It hasn't helped :(
